POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJyb250dG8iLCJpZCI6IjYyYzFjMmJhODZiNjdjNmM5NDVkOTM2ZSIsImlhdCI6MTY1Njg2OTYyNSwiZXhwIjoxNjU2ODczMjI1fQ._xZS68X44gyFKAt3JnX9GfAfgYZjSDD_rhvy6f2AnME

{
    "title": "Jolo Blogi",
    "author": "Markku Jooseppi",
    "url": "http://linkkimoi.com",
    "likes": 19
}